@node Introduction
@chapter Introduction

The @sysname{} library provides protocols and implementations of those
protocols for text editing operations which are required by, for
example, text editors or commandline processors (like REPLs).  Some of
the concepts and naming used in this library are inspired by Emacs but
the functionality should be generic enough to be build other kinds of
Editors as well.  This library relies on the
@uref{https://github.com/Robert-Strandh/cluffer,Cluffer library} for the
fundamental concepts of buffers, lines and cursors.

The functionality provided by this library includes:

@itemize

@item
@ref{Motion Operations,Cursor movement} (by various ``@ref{term-unit,units}'')

@item
@ref{Insertion Operations,Insertion} and @ref{Deletion
Operations,deletion} (by various ``units'')

@item
Transformations like
@ref{Generic-Function text.editing|change-case,changing case}
or @ref{Generic-Function text.editing|transpose,transposing}

@item
Operations on expression (like
@uref{https://paredit.org/,paredit for Emacs}, work in progress)

@item
Undo (work in progress)

@item
@ref{Copy and Yank Operations,Killing@comma{} copying and inserting}

@item
@ref{Multiple Sites Protocol,Multiple cursors}

@item
Search (work in progress)

@item
Abbreviations (work in progress)

@end itemize

The @sysname{} library does not provide:

@itemize

@item
Data structures for editor buffers (the
@uref{https://github.com/robert-strandh/cluffer,Cluffer library} does
that)

@item
Input handling or a command processor (This aspect obviously heavily
depends on the application and there are many ways to do it.
@uref{https://codeberg.org/McCLIM/McCLIM, McCLIM} is one library
provides both input handling and command processing.)

@item
Advance parsing (the
@uref{https://github.com/robert-strandh/incrementalist,Incrementalist library}
does that)

@item
Syntax highlighting

@item
Presentation/rendering/display functions for the contents of text
buffers (Like command processing, this aspect heavily depends on the
application it.  Again, @uref{https://codeberg.org/McCLIM/McCLIM,
McCLIM} is one library that could be used.)

@end itemize
