\input texinfo

@include macros.texi
@include generated-version.texi

@documentencoding UTF-8
@documentlanguage en

@syncodeindex vr fn
@syncodeindex tp fn

@paragraphindent 0

@setfilename text.editing.info
@settitle @sysname{} User's Manual

@copying
Copyright @copyright{} 2023, 2024 Jan Moringen
@end copying

@dircategory Common Lisp
@direntry
* text.editing User's Manual: (text.editing). A generic text editing library.
@end direntry

@titlepage
@title @sysname{} User's Manual

@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top @sysname{} User's Manual

This manual is for @sysname{} version @sysversion{}.
@end ifnottex

@menu
* Introduction::
* Concepts::
* External Protocols::
* Search::
* Expressions::
* Equivalent Emacs Commands::
* Concept index::
* Function and macro and variable and type index::
@end menu

@include chapter-introduction.texi

@include chapter-concepts.texi

@include chapter-external-protocols.texi

@include chapter-search.texi

@include chapter-expressions.texi

@include generated-chapter-equivalent-emacs-commands.texi

@node Concept index
@unnumbered Concept index

@printindex cp

@node Function and macro and variable and type index
@unnumbered Function and macro and variable and type index

@printindex fn

@c TODO @include chapter-changelog.texi

@bye
